services:
  - type: web
    name: whisperwall
    env: python
    buildCommand: cd whisperwall && pip install -r requirements.txt && python manage.py collectstatic --noinput --no-post-process
    startCommand: cd whisperwall && gunicorn whisperwall.wsgi:application --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: DJANGO_DEBUG
        value: 'False'
      - key: PYTHONUNBUFFERED
        value: '1'
    plan: free
