# Generated by Django 6.0.2 on 2026-02-06 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('emotion', models.CharField(choices=[('love', 'Love'), ('crush', 'Crush'), ('heartbreak', 'Heartbreak'), ('regret', 'Regret')], max_length=20)),
                ('location_hint', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('confession_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_a', to='core.confession')),
                ('confession_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_b', to='core.confession')),
            ],
        ),
    ]
