# Generated by Django 6.0.2 on 2026-02-12 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevealRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confession_a_accepted', models.BooleanField(default=False)),
                ('confession_b_accepted', models.BooleanField(default=False)),
                ('revealed', models.BooleanField(default=False)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.match')),
            ],
        ),
    ]
