# Generated by Django 6.0.2 on 2026-02-20 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_revealrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='is_revealed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confession', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.confession')),
            ],
        ),
    ]
