# Generated by Django 6.0.2 on 2026-02-25 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_confession_is_revealed_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='confession',
        ),
        migrations.AddField(
            model_name='confession',
            name='author_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confessions', to='core.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='device_signature',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='confession',
            name='emotion',
            field=models.CharField(choices=[('love', 'Love'), ('crush', 'Crush'), ('heartbreak', 'Heartbreak'), ('regret', 'Regret'), ('fight', 'Fight'), ('miss', 'Missing You'), ('apology', 'Apology')], max_length=20),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('plan', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.match')),
            ],
        ),
    ]
