# Generated by Django 6.0.4 on 2026-04-24 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_password_reaction_live'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confession',
            name='author_profile',
        ),
        migrations.RenameField(
            model_name='live',
            old_name='match',
            new_name='event',
        ),
        migrations.RemoveField(
            model_name='live',
            name='Reaction',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='profile',
        ),
        migrations.AddField(
            model_name='confession',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reaction',
            name='confession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.confession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reaction',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment')], default='like', max_length=10),
        ),
        migrations.AddField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='live',
            name='reaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reaction'),
        ),
    ]
