# Generated by Django 6.0.4 on 2026-04-25 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_confession_author_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='emotion',
            field=models.CharField(choices=[('course_help', 'Course Help'), ('project_team', 'Project Team'), ('exam_preparation', 'Exam Preparation'), ('study_group', 'Study Group'), ('internship_advice', 'Internship Advice'), ('administrative_request', 'Administrative Request'), ('lost_found', 'Lost / Found'), ('love', 'Love'), ('crush', 'Crush'), ('heartbreak', 'Heartbreak'), ('regret', 'Regret'), ('fight', 'Fight'), ('miss', 'Missing You'), ('apology', 'Apology')], max_length=30),
        ),
        migrations.CreateModel(
            name='AcademicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('academic_email', models.CharField(max_length=255)),
                ('programme', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
